import type { Person, Relationship } from "@/lib/types";

const now = "2026-04-21T00:00:00.000Z";

export const mockPersons: Person[] = [
  {
    id: "p-001",
    internal_code: "ROOT-01",
    name: "김양수",
    gender: "male",
    birth_date: "1932-03-12",
    lunar_birth_date: null,
    phone: null,
    address: "강원특별자치도 강릉시",
    generation: 1,
    branch_code: "ROOT",
    family_role_type: "blood",
    deceased: true,
    death_date: "2001-08-20",
    burial_place: "강릉 선영",
    memo: "가족 계보의 기준 인물",
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-002",
    internal_code: "ROOT-01-S",
    name: "이정숙",
    gender: "female",
    birth_date: "1936-11-03",
    lunar_birth_date: null,
    phone: null,
    address: "강원특별자치도 강릉시",
    generation: 1,
    branch_code: "ROOT",
    family_role_type: "spouse",
    deceased: true,
    death_date: "2014-01-15",
    burial_place: "강릉 선영",
    memo: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-101",
    internal_code: "BR01-02-001",
    name: "김영호",
    gender: "male",
    birth_date: "1958-05-09",
    lunar_birth_date: null,
    phone: "01011112222",
    address: "서울특별시",
    generation: 2,
    branch_code: "BR01",
    family_role_type: "blood",
    deceased: false,
    death_date: null,
    burial_place: null,
    memo: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-102",
    internal_code: "BR01-02-001-S",
    name: "박미경",
    gender: "female",
    birth_date: "1961-02-21",
    lunar_birth_date: null,
    phone: "01022223333",
    address: "서울특별시",
    generation: 2,
    branch_code: "BR01",
    family_role_type: "spouse",
    deceased: false,
    death_date: null,
    burial_place: null,
    memo: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-103",
    internal_code: "BR02-02-001",
    name: "김선희",
    gender: "female",
    birth_date: "1962-09-18",
    lunar_birth_date: null,
    phone: "01033334444",
    address: "경기도 성남시",
    generation: 2,
    branch_code: "BR02",
    family_role_type: "blood",
    deceased: false,
    death_date: null,
    burial_place: null,
    memo: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-104",
    internal_code: "BR02-02-001-S",
    name: "최재문",
    gender: "male",
    birth_date: "1960-12-04",
    lunar_birth_date: null,
    phone: null,
    address: "경기도 성남시",
    generation: 2,
    branch_code: "BR02",
    family_role_type: "spouse",
    deceased: false,
    death_date: null,
    burial_place: null,
    memo: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-201",
    internal_code: "BR01-03-001",
    name: "김민준",
    gender: "male",
    birth_date: "1987-07-24",
    lunar_birth_date: null,
    phone: "01044445555",
    address: "서울특별시 마포구",
    generation: 3,
    branch_code: "BR01",
    family_role_type: "blood",
    deceased: false,
    death_date: null,
    burial_place: null,
    memo: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-202",
    internal_code: "BR01-03-002",
    name: "김하늘",
    gender: "female",
    birth_date: "1990-10-02",
    lunar_birth_date: null,
    phone: "01055556666",
    address: "서울특별시 송파구",
    generation: 3,
    branch_code: "BR01",
    family_role_type: "blood",
    deceased: false,
    death_date: null,
    burial_place: null,
    memo: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "p-203",
    internal_code: "BR02-03-001",
    name: "김도윤",
    gender: "male",
    birth_date: "1992-04-14",
    lunar_birth_date: null,
    phone: "01066667777",
    address: "경기도 성남시",
    generation: 3,
    branch_code: "BR02",
    family_role_type: "blood",
    deceased: false,
    death_date: null,
    burial_place: null,
    memo: null,
    created_at: now,
    updated_at: now,
  },
];

export const mockRelationships: Relationship[] = [
  {
    id: "r-001",
    from_person_id: "p-001",
    to_person_id: "p-002",
    relationship_type: "spouse",
    created_at: now,
  },
  {
    id: "r-002",
    from_person_id: "p-001",
    to_person_id: "p-101",
    relationship_type: "parent",
    created_at: now,
  },
  {
    id: "r-003",
    from_person_id: "p-001",
    to_person_id: "p-103",
    relationship_type: "parent",
    created_at: now,
  },
  {
    id: "r-004",
    from_person_id: "p-101",
    to_person_id: "p-102",
    relationship_type: "spouse",
    created_at: now,
  },
  {
    id: "r-005",
    from_person_id: "p-103",
    to_person_id: "p-104",
    relationship_type: "spouse",
    created_at: now,
  },
  {
    id: "r-006",
    from_person_id: "p-101",
    to_person_id: "p-201",
    relationship_type: "parent",
    created_at: now,
  },
  {
    id: "r-007",
    from_person_id: "p-101",
    to_person_id: "p-202",
    relationship_type: "parent",
    created_at: now,
  },
  {
    id: "r-008",
    from_person_id: "p-103",
    to_person_id: "p-203",
    relationship_type: "parent",
    created_at: now,
  },
];
